### ISSUE TITLE
ExportPresenter should not strictly depend on existing series

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#1]
ExportPresenter inherits SeriesPresenter -- the idea is to always provide `series` parameter in SQL queries. SeriesPresenter enforces that at least one series must exist -- this doesn't apply to ExportPresenter though, SQL queries should handle any (even non-existent) series number, and many exports don't use the `series` parameter at all.

Suggestion: in the context of ExportPresenter, SeriesChooser should offer `really existing series` and `{1,2,3,4,5,6}` (as safe default).

**Comment by cevro** [comment]
In https://github.com/fykosak/fksdb/pull/129 contestNav(new contestChooser) contains always seriesChooser, that solve this issue.

**Comment by cevro** [comment]
Every presenter in OrgModule is strictly depended on series context. This solve this issue.
