### ISSUE TITLE
Seznam budov do výsledkovek se nebere z DB

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#105]
Ale je tam nějak hardcodovaný.

**Comment by cevro** [comment]
Generovanie filtrov by malo prebiehať v DB a napr. pomocou data-* atribútu posunúť klientovi.

**Comment by cevro** [comment]
- Vyriešiť tahanie miestností z FKSDB
- ťahať usadenie týmov z FKSDB (prepísať na nový spôsob)

**Comment by cevro** [comment]
Vyriešené https://github.com/fykosak/nette-brawl-lib/commit/341a658d626835fcb80a27e805a766a6af2c1fa1
