### ISSUE TITLE
Hlášky při submitu

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#106]
Při odesílání submitu pomocí QR kódu ve chvíli, kdy je tým neodprezentovaný se zobrazí jak success tak error flash message. Submit to vezme.

**Comment by cevro** [comment]
Pri odoslaní stačí premserovať na fyziklani:entry bez ID presmerováva sa teraz na 'this' teda tá istá stránka aj s IDčkom.

**Comment by cevro** [comment]
Presmerovanie by malo byť na túto stránku bohužiaľ, asi to tak triviálne nepôjde.
https://github.com/fykosak/fksdb/issues/232

**Comment by cevro** [comment]
riešené v https://github.com/fykosak/fksdb/pull/245
