### ISSUE TITLE
Odpocet na vysledkovkach preskakuje.

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#107]
Duvodem je vysoka latence, pak pri dalsim syncu hodin se serverem cas poskoci.

**Comment by timkol** [comment]
Implementovat synchronizaci z NTP.

**Comment by LukasLedvina** [comment]
[Zde](http://www.presnycas.cz/) dokáží změřit rozdíl času mezi lokálním PC a etalonem. Takže bych to dělal tak, že se změří rozdíl mezi lokálním PC a fykosím serverem (jiným serverem), pak se bude čas zobrazovat dle lokálního PC. Ten čas na lokálním PC se zas tak moc během soutěže nerozhodí.

**Comment by cevro** [comment]
Ani jedno nebude potrebné, zistil som, že chyby boli 2 a to to že setTimenout nieje presný teda sa nedá na to plne spoľahnuť. Druhá vec je, že props sa predáva Timeru až po vykreslení tabuľky, kde bol nechutný dlhý proces vykreslenia a spomaľoval predanie upadnutie časov. V zálohe mám ešte update na spomaľovanie a zrýchľovanie času na dorovanie.

**Comment by cevro** [comment]
rieši sa v https://github.com/fykosak/fksdb/pull/121

**Comment by cevro** [comment]
Vyriešné, nasadené

**Comment by cevro** [comment]
Nieje, 
potreba vyriešiť ešte čas requestu a započíta ho do času.
https://stackoverflow.com/questions/3498503/find-out-how-long-an-ajax-request-took-to-complete
