### ISSUE TITLE
Fixnúť farbu v hlavičke tabuliek pre série

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#1108]
@vercah : Fixnúť farbu hlavičky a "medzihlavičky" v seriesTable po prechode na bootstrap 5.1 viď https://files.slack.com/files-pri/T3TDZ9S68-F02T7LQK2DR/image2.jpg

**Comment by vercah** [comment]
Teď jsem na to koukala a buď to někdo udělal, nebo se to samovolně fixnulo, protože na produkci už to je modré :D

**Comment by cevro** [comment]
Ako som písal na slacku, produkcia bola revertnutá, teda sa to tam neprejavuje.
