### ISSUE TITLE
Kompilovanie JS

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#111]
Poskytovať JS skompilovaný v jednom súbore.

Výhody:
- možnosť používať ES6 a ES7+
- možnosť používať typescript
- riešenie závislosti priamo v súboroch cez importy
- menšia zátaž pri načítavaní
- odpadá asynchrónne načítanie externých skriptov.
- lepšia prehľadnosť a možnosť delenia na komponenty

nevýhody:
- Nette JS sú písane cez prototypy a nie modulárne, nutnosť prepísať, upraviť
- Zvyšuje dev dependencie
- Asi čiastočne zvýši prenášaný objem.

Výhoda/nevýhoda
- je to neprebádaná oblasť pretože Nette-kinder mafia je konzervatívna a všade pchá jQuery, ktoré je založené na prototypovanií.

**Comment by Werkov** [comment]
Přichystáno v dev-fof-results-redux, includuje nový modul.

**Comment by cevro** [comment]
Myslím, že sa to dosť dobre vyriešilo v nette-brawl-lib
