### ISSUE TITLE
Opravit a refaktorovat ContestChooser

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#116]
- Občas hází 403 nebo 500,
- ujasnit, zda a jak seřadit semináře na výběr,
- zjednodušit (rozdělit).

Tisíce neděkovných dopisů.

**Comment by cevro** [comment]
500 by už nemala naskakovať, bol to error eventov.

**Comment by cevro** [comment]
rieši sa v https://github.com/fykosak/fksdb/pull/129
