### ISSUE TITLE
Stalkovanie osôb v DB

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#120]
Celkom dlho uvažujem nad stalking stránkou na webe/FKSDB.

Celá pointa je taká, že by to bolo stránka, kde sú všetky potrebné údaje o človeku a čo o nich máme.

- Meno
- email
- Adresa 
- telefón/telefón na rodičov
- ďalšie informácie
- aktuálna škola+adresa školy
- [historické adresy školy/ročníky]
- jeho adresa (kontaktná trvala)
- pôsobenie vo FYKOSe 
  - akcie (org + účastník)
  - serie čo odovzdal počty bodov...

Pomôcť by to malo hlavne importe a kontrole importe starých účastníkov, rýchly a pohodlné hľadanie adries hocičoho potrebného, a do budúcna časť informácii by mohla isť na web - tj hlavne účasť v akciách a sériach.

**Comment by syselkk** [comment]
+ 1
Mimochodem - k tomu telefonu na rodiče - o tom Verča říkala jako zdravotník, že by to tam asi ráda měla - a jestli se pamatuju, tak se to nikdy dřív nesbíralo v přihlášce. On by to mohl být "kontaktní telefon v případě nouze" - a jedna kolonka by se vyplňovala číslo telefonu a druhá, na koho to vlastně je (abychom byli genderově korektní a taky korektní vůči sirotkům apod.). Ale aby to mělo smysl, tak by se to muselo vyžadovat u přihlášek.

**Comment by Werkov** [comment]
👍 
> časť informácii by mohla isť na web - tj hlavne účasť v akciách a sériach.

Tzn. udělat to přes export (s důrazem na oprávnění)? Anebo linkovat na implementaci ve FKSDB?

Ať tak či onak, bylo by dobré udělat to nějak modulárně (např. profil osoby má formu nějaké abstraktní datové struktury (strom + seznamy) a deklarativně se popíše, co a jak jde na výstup) , aby to bylo rozšiřitelné.

**Comment by timkol** [comment]
Jsem pro to, aby pro web nebylo přidáno další API, ale byly použity exporty. Pro uživatele se něco může udělat, ale je otázka, jaká na to dát práva, pokud tam chceš tolik informací (IMO jsem pro ~ stejná, jako export-execute). Jinak je to spíš challenge pro UI/UX, navrhnout to tak, aby se to dobře používalo.

**Comment by cevro** [comment]
@timkol  veľmi ťažko to narveš do nejaké (rozumnej) tabuľkovej formy, akú majú teraz exporty na web. Preto, ak to časom  budeme chcieť dostať na web, bude treba vymyslieť obecnejší mechanizmu ako netabuľkové štruktúry budeme prenášať. 

Ďalší problémom je, v prípade viacerých exportov/netabuľkových nemáme prostriedky ako ich korektne stiahnuť a preprocesovať na strane webu.

Osobne by som sa zmeral vytvoriť implementáciu vo FKSDB a ak sa osvedčí a ukáže sa ako zaujímavá/prospešná, tak uvažovať nad rozšírením/exportovaním. 

ad prava: jedna možnosť je obmedziť prístup, druhá je obmedziť to čo sa komu zobrazí, teda k dajnej komponente(modulu).

Komponenty by asi mali byť:
aktualne info
`BaseInfo` -> dátum narodenia, OP,...
`ITInfo` -> login, login ID, má heslo...
`OrgInfo` -> je org v akých semiaroch, odkedy dokedy, čo robil, robí ... 
`ContactInfo` ->telefón  (na rodičov), email
`CurrentAddess` (Kontaktná + trvalá) -> adresy
`CurrentSchool` -> informácie o aktuálnej škole
historické info 
`HistoricAddess` -> záznam všetkých starých adries
`HistoricSchool` -> informácie o predchádzajúcich školách
Akcie [účastník]
`Participant` -> info o každej akcií teda kedy, kde, čo zač.
Akcie [org]
`Org` -> info o každej akcií teda kedy, kde, čo zač.

**Comment by cevro** [comment]
Niečo som nastrelil do https://github.com/fykosak/fksdb/tree/dev-stalking

Nieje tam ešte vyhľadávací formulár takže to ešte nejde do PR.

**Comment by cevro** [comment]
Ešte obrázok:
najcitlivejšie údaje boli premazamé, menej citlivé rozmazané, je to moja lokálna kopia dát, teda neaktualne a poznačené testovaním.

![stalk](https://cloud.githubusercontent.com/assets/10603313/26727861/90b9cd14-47a8-11e7-9e89-0f079823b0ac.png)

**Comment by Werkov** [comment]
Vyřešeno v #147.
