### ISSUE TITLE
Defaultně nabízet skupinu programu, ze které se otevřelo vytváření položky

### ISSUE THREAD

**Issue by vercah** [fykosak/fksdb#1259]
"bug" report / feature request – když kliknu na "vytvořit položku" zatímco mám otevřenou nějakou skupinu, v tom vytváření položky musím ještě znovu zvolit, do jaké skupiny programu to chci přidat. Dalo by se to udělat tak, že tam bude automaticky zvolená ta skupina, kterou jsem měl otevřenou?

**Comment by cevro** [comment]
Hovotov
