### ISSUE TITLE
Jednokliková prezentace

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#1297]
Pokud přijede tým, který má v prezenční listině vše OK a beze změn, tj. stačí je jen přesunout z Approved->Participated.

Aktuálně je třeba najít tým, rozkliknout ho, scrollovat a pak dát změnu stavu.

Přidat tlačítko na změnu stavu rovnou do seznamu týmů, aby byla možná rychlá prezence jedním klikem (a ideálně AJAXově).

**Comment by cevro** [comment]
riešené tu: https://github.com/fykosak/fksdb/pull/1313
