### ISSUE TITLE
Rozklikávací formulář týmu

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#1300]
Formulář týmu při prezentaci (editaci přihlášky) je dlouhý na mnoho obrazovek. Údaje o členovi, program a to vše násobené počtem členů. Taková stránka je obtížná na obsluhu a navigaci ve formuláři.

Udělat formulář rozklikávací podle sekcí: per člen a program člena. Tak, aby v základním zobrazení bylo vidět jen přehled atributů týmu a jména členů týmů.

**Comment by cevro** [comment]
Asi fixnuté
