### ISSUE TITLE
Registrace řešitele FoLu/FoFu do série

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#131]
Pokud někdo řeší prvně FoL nebo FoF a pak se chce registrovat do série, má záznam v person, ale nemá záznam v login. Tudíž se nemůže přihlásit, ani registrovat (osoba již existuje, resp.: "Zadané údaje se neshodují s již uloženými."). Řešením je pak dát zapomenuté heslo. A pak se po přihlášení znovu registrovat.

Možná řešení:
1) Přidat do registračního formuláře text: "Pokud jste již řešili FoL nebo FoF, pokračujte na zapomenuté heslo."
2) Udělat registrační formulář vícestavový. Zadají mail a podle něj je to přesměruje správným směrem.
3) Opravit mergeovací strategii údajů, aby reg. formulář fungoval, i když zadají stejné údaje.
4) Opravit hlášku, aby naváděla na to, že už jsou v DB.
5) Všem účastníkům FoLu a FoFu zároveň zakládat loginy do FKSDB.

**Comment by cevro** [comment]
rieši sa v https://github.com/fykosak/fksdb/pull/129
