### ISSUE TITLE
Renderovanie formulárov pod bootstrap.4.0

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#140]
Formuláre sa vo FKSDB renderujú 3-ma renderermi, 

- Nette rendererom - defaultny nepodporuje bootstrap.
- Bootstrap rendererom z Kdyby knihovne,
- Rendererom vo libFKS

Pre jednoduchosť by som jeden z dvojice bootstrap/libFKS prestal používať a formuláre prepísal pod bootstrap.4.0, a používal pre jednoduchosť len jeden.

Prip. pohľadať vhodnú knihovňu kompatibilnú s bootstrapom4

**Comment by Werkov** [comment]
> Nette rendererom - defaultny nepodporuje bootstrap.
- snad se nepoužívá, takže lze ignorovat

> Bootstrap rendererom z Kdyby knihovne,
- už byl přepis 2->3, takže taky by měl jít

> Rendererom vo libFKS
- má template, měl by jít přepsat
