### ISSUE TITLE
Seznam států by měl být v angličtině

### ISSUE THREAD

**Issue by sstenchlak** [fykosak/fksdb#141]
Bylo by lepší mít seznam států v anglickém jazyce, nikoli v originálním jazyce daného státu. Špatně se pak hledá třeba Čína, když je to jako 中华人民共和国.

**Comment by syselkk** [comment]
O jaký seznam jde? O seznam států účastníků, když se hlásí? To by mohly být česky/anglicky podle jazyka DB, ve kterém se daná osoba hlásí.
(Pokud by šlo ale o seznam jazyků, tak ten naopak má být v původním, protože všichni neznají svůj jazyk ve všech ostatních jazycích...)

**Comment by timkol** [comment]
Jde o seznam v tabulce region, který je zatím využíván jen při přidávání školy. Předělám to, zpátky to kdyžtak jde dát vždycky.

**Comment by syselkk** [comment]
Jo tak jestli to je jenom v místě, kde se vyplňuje v angličtině přihláška, tak máš pravdu, že je to OK. Jenom pak je na to třeba časem myslet, kdyby někdo chtěl něco nějak rozšiřovat na další aplikace...

**Comment by timkol** [comment]
Až na ČR a SR (a ty se přeložit nesmí, páč se to používá na obálky) je to přeloženo. Zavírám.
