### ISSUE TITLE
SelectBox -- translate items & label

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#158]
Select box má psychický problém s prekladmi
Keď sa použije `_()` funckcia, select vyhodí  `Object of class stdClass could not be converted to string`

Zároveň sa label neprekladá aj napriek použitiu `_()`.

**Comment by Werkov** [comment]
Formulářové popisky by se měly překládat pomocí použítí `Translator`u v Nette formulářích.

https://github.com/fykosak/fksdb/blob/master/libs/Nette/Forms/Controls/BaseControl.php#L390
https://github.com/fykosak/fksdb/blob/master/libs/Nette/Forms/Controls/SelectBox.php#L222

Objekty přihláškového automatu a holderu (`Field`) by [měly být překládány](https://github.com/fykosak/fksdb/blob/master/app/model/Events/EventsExtension.php#L518) pomocí `_()` v Neonu.

Je třeba přegenerovat (`i18n/extract.sh`) a přeložit nové texty (Poedit).
Jak přemýšlím nad těmi formuláři výše, tak může být nutno upravit `extract.sh`, aby zahrnoval i textové údaje mimo `_()` (protože to ty formuláře nepoužívají).
