### ISSUE TITLE
log bez hesla ....

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#170]
HT: težká http://db.fykos.cz/application/default/2183?eventId=3&bc=TCFB&_fid=lyx2 ide sa prihlásiť a dostať do acc len na základe linku.....

**Comment by Werkov** [comment]
@cevro je to stále aktuální? Nebyl tím myšlen link s tokenem?

**Comment by cevro** [comment]
@Werkov ano bol to ak si dobre spomínam, a momentálne sa stále dá prihlásiť na základe linku. 

Otestované na linku u FoFu

**Comment by Werkov** [comment]
Aha, já jsem to měl za feature.

Ty bys to chtěl omezit jen na prohlížení/editaci dané přihlášky?

**Comment by cevro** [comment]
Obecne sa mi nepáči, že ťa len na základe tokenu prihlási do FKSDB. Predsa len je to mail, a dosť často napr. tu FoFu/FoLu sa maily preposielajú učiteľom/spolužiakom.

**Comment by Werkov** [comment]
Ano, to je ta dnešní mládež :-)

Riziko zobrazení osobních údajů je tak jako tak. V těch ostatních částech FKSDB už toho zas tolik neudělají (pokud nejsou orgové Výfuku). Úprava by zasahoval do základu přihlašovacího mechanismu.

Jednodušší by tedy bylo tyhle odkazy z mailu odebrat a nahradit je přihlašováním (což by se jim stejně posílal mail s tokenem, ale byl by jiný, takže by ho nemuseli chtít přeposílat).

Anebo posílat dva maily -- jeden s tokenem (a bububu) a druhý s detaily přihlášky.

**Comment by timkol** [comment]
Jsem pro přidání generického bububu do mailů s tokeny a jinak to neřešit.
