### ISSUE TITLE
O RLY confirmation

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#179]
Když na mě vyskočí okno, jestli fakt souhlasím, tak tam napsat s čím mám souhlasit (jméno a akce nebo alespoň akce).

**Comment by cevro** [comment]
@timkol nieje toto už vyriešené?

**Comment by timkol** [comment]
co já vím, z popisu nechápu, v čem byl problém (jaké okno vyskakovalo). @syselkk hádám, že je to od tebe, jsi se současným stavem spokojen?
