### ISSUE TITLE
invalid cashe after install

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#18]

**Comment by Werkov** [comment]
Cache is [updated](https://github.com/fykosak/fksdb/blob/master/install.sh#L56), however, my guess is that certain [submodules fail](https://github.com/fykosak/fksdb/blob/master/install.sh#L46)

**Comment by timkol** [comment]
Still reproducible or solved by #29 ?

**Comment by Werkov** [comment]
Problem disappeared (not observed in last 10 moths).
