### ISSUE TITLE
Chybová hláška 'Organizátor již existuje.'

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#185]
V ReferencedPersonPresenteru se chytá jakákoli DB výjimka, ale vždy se vypisuje tato hláška (ta hláška nemusí nutně odpovídat skutečné výjimce). Objevit dle čeho lze rozlišit výjimky a podle toho zobrazit patřičnou (nematoucí) hlášku.

**Comment by timkol** [comment]
IMO už je vyřešeno.
