### ISSUE TITLE
Nefungují backlinky přes session

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#199]
HT: težká 
- cross domain, při přístupu nepřihlášeným uživatelem na autentizovací stránku

**Comment by Werkov** [comment]
@cevro Co tohle vyřešit zrušením samostatné [auth](https://github.com/fykosak/fksdb/blob/master/app/config/router.neon#L21) domény? (Za předpokladu, že FKSDB účty se používají jen k přihlášení k FKSDB a pokud by je bylo třeba rozšířit v budoucnu, tak to udělat standardním způsobem,)
Potenciální nevýhoda: uživatelstvo s password managery, kteří mají uložená hesla pro auth. doménu (je to otrava, ale nikoliv úplná ztráta loginu (manuální překopírování).)

**Comment by cevro** [comment]
@Werkov see: https://github.com/fykosak/fksdb/pull/1016

PassManager v chrome zvláda zmenu subdomény celkom dobre.

**Comment by Werkov** [comment]
Backlinky pro nepřihlášeného uživatele již fungují \o/.
I FF se s tím umí srovnat (nabídne podle domény 2. řádu.)
