### ISSUE TITLE
CSS preprocesor

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#21]
Zišiel by sa do DB css preprosesor, BUNO. S[AC]SS alebo LESS, hlavne nech tam nejaký je lebo sa csska píšu príšerne.

**Comment by timkol** [comment]
Nemám výhrad, ale ať je právě jeden. Osobně lobbuji spíše za něco co překládá (a minifikuje) do CSS na straně vývoje typu Grunt nebo Gulp, spíš než za nějaký js preprocesor na straně klienta.

**Comment by cevro** [comment]
Skôr som za preprocesor priamo na serveri trebars rýchlym gogolením
http://leafo.net/scssphp/

Zkomplilovať vie skoro každé IDE ale to nechcem, a klient site je závislí na externom JS. Čo sa mi nepáči.

**Comment by timkol** [comment]
Na té službě se mi nelíbí, že poskytování statických souborů děláš PHP skriptem (pokud to dobře chápu). Nemůžeš pak třeba použít rozumně cachování statických souborů a celkově ti to poskytuje šnek zvaný PHP. Těch pár ušetřených kliknutí při vývoji za to IMO nestojí.

**Comment by Werkov** [comment]
Do produkce jsem určitě za staticky kompilované templaty a gitování hotových CSS (zjednoduší to instalační skript a závislosti na instalačních prostředích).

Na druhou stranu se nebráním nečemu, co na vývojovém prostředí (nějakým konfiguračním swtichem) dovede on-demand překládat na klientovi.

**Comment by cevro** [comment]
Jedná sa mi hlavne o vývoj, preto som myslel vykompilovať css raz, (asi) pri inštalácii a poskytovať ich staticky. Ak chcete uchovávať aj css v gite, tak potom to vyriešil u seba IDEčkom, ktoré mi css vykompiluje a v princípe to scss môžem aj zagitovať. 
Osobne som pre scss, pretože podľa zákulisných drbov to bude css4 

Bootstrap sa poskytuje aj ako Less aj ako Sass. Inak v DB ho tam máme skompilovaný a minimalizovaný.

**Comment by Werkov** [comment]
On Tue, Dec 06, 2016 at 06:04:00PM -0800, Michal Červeňák <notifications@github.com> wrote:
> Jedná sa mi hlavne o vývoj, preto som myslel vykompilovať css raz, (asi) pri inštalácii a poskytovať ich staticky.
Statické vykompilování do produkce +1
Při instalaci -1 (viz argumetny výše)

> Osobne som pre scss, pretože podľa zákulisných drbov to bude css4 
Jestliže je to scss kompatibilní s Bootstrapem (o ten jde ve FKSDB
hlavně), tak proč ne.

Jelikož je FKSDB přes Bootstrap jsou nějaké jiné důvody pro preprocesor?

**Comment by cevro** [comment]
Po dlhšiom čase asi možná implentácia:

- oddelenie source niekam mimo www/caa
- budú v SCSS -> je to z časti kompatibilné s CSS4
- preklad na strane vývoja a gitovanie hotových css

**Comment by cevro** [comment]
Terajšia implentácia:
vo `/var/www/css/sccs/` sa ukladajú súbory sccs.

kompilácia pomocou https://www.sassmeister.com/
