### ISSUE TITLE
Application import doesn't work for team events

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#22]
I tried to use csv import for transition of states of OPB participants and it didn't work. Failed on 'wrong CSV header' identified on https://github.com/fykosak/fksdb/blob/aa180af276bf62d7f9ecc3a40eb5ee145a18bdfd/app/model/Events/Model/ImportHandler.php#L118

Neither works with e_fyziklani_team_id;status nor name;status header.

**Comment by Werkov** [comment]
Strange, can't reproduce with aa180af276bf62d7f9ecc3a40eb5ee145a18bdfd.

My sample CSV looked like:

    name;status
    Foobar;applied

The team previously didn't exist and was created (without members (I had to circumvent division by zero in [CategoryProcessing](https://github.com/fykosak/fksdb/blob/aa180af276bf62d7f9ecc3a40eb5ee145a18bdfd/app/model/Events/Spec/Fol/CategoryProcessing.php#L142)).
