### ISSUE TITLE
Prekopať prihlasovanie na FOF

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#253]
Súčasné problémy:
- Vyhladávač osoby nevyžaduje striktne email, časť užívateľov zadá to kolonky meno "vyhľadá osobu" a potom vyplní osobu s existujúcim mailom vo FKSDB, čo vedie k erroru "niektoré dáta sa nezhodujú už s uloženými".
  - striktne vyžadovať mail, 
  - zakázať zmenu mailu po vyhľadaní osoby
  - prepísať to tak aby bolo jasné že tam treba mail.

- Osoba je jednoznačne zviazaná s emailom, pri zmene údajov pri registrácii sa nedá zmeniť mail, bez toho aby sme si vyťahovali dáta.
  - povoliť úpravu mailu

- Náhrada osoby je komplikovaná 

- troška krajšie GUI :)

**Comment by syselkk** [comment]
Pokud bude překrývající se přihlašování na FOF a FoL, tak

- 1. krok po vstupu přihlášky by měl být jenom text cca o tom, že "If you do not understand Czech, switch languages (up right corner). <br /><br /> Zde se přihlašujete na soutěž FYKOSí Fyziklání, která se koná X.Y.ZZ **v Praze**. Současně probíhá v rámci jiné přihlášky přihlašování na jinou internetovou soutěž Fyziklání online, která probíhá po internetu." a pod tím sugestivní tlačítko "Chci se přihlásit do Prahy".

Pokud chceme zahraniční týmy

- nezapomenout přidat rozbalovací menu nebo tak něco: "Chci soutěžit v češtině/I want to compete in English" (přednastavené by to mohlo být podle jazyka přihlášky)
- zvážit možnost delšího ubytování a objednání ubytování "od" "do" (s tím, že by ty další dny, krom toho před soutěží, platili celé) - je to ale spíš připomínka k Danovi, jak to chce řešit

A raději mi pošlete pak nějakou testovací verzi, abych vám to mohl zkritizovat před ostrým provozem ;-)

**Comment by cevro** [comment]
Hotovo
