### ISSUE TITLE
viacúrovňové ACL pre stalking

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#262]
pridať rôzne módy (úrovne práv) do stalkingu

**Comment by cevro** [comment]
Pointou je aby si časť dát, vedel zobraziť každý org. prip. org s nejakým stupňom práv a zbytok bol skrytý.

**Comment by syselkk** [comment]
Jo - přesně - zatím to stále ukazuje, že nemám práva na účastníky Fyziklání apod. ...
