### ISSUE TITLE
Tester submodule points to nonexistent commit

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#27]
git submodule update command on fresh install writes: 

fatal: reference is not a tree: 21998e56aa5c446e3efbc65b95ffa5cd656d9e39
Unable to checkout '21998e56aa5c446e3efbc65b95ffa5cd656d9e39' in submodule path 'tester'

Indeed this commit doesn't exist in github.com/nette/tester repository.
@Werkov

**Comment by Werkov** [comment]
I hope self-approval is OK in this non-code change.
