### ISSUE TITLE
Vlajočky štátov

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#280]
Nájsť vhodnú sadu vlajočiek a dostať ju do FKSDB.

**Comment by cevro** [comment]
Na lokálnom prostredí používam https://github.com/lipis/flag-icon-css/

**Comment by timkol** [comment]
Jsou sice občas trochu divně ořízlé, ale to je tou stejnou velikostí. Nic lepšího jsem nenašel. Takže jsem pro.
