### ISSUE TITLE
[FOF] Poradie úloh

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#37]
Úlohy sa zle radia z DB
`ORDER BY label` vráti najskôr label EE potom až CH.

**Comment by timkol** [comment]
Je potřeba nastavit správnou collation (utf8_general by mohla fungovat)
u daného sloupce (příp. na celou tabulku, pokud tam nejsou jiné textové
sloupce). V české je Ch (1 písmeno) po E.

**Comment by cevro** [comment]
Dik opravné na teste funguje.
