### ISSUE TITLE
Mišo rozmlatil stamper

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#396]

**Comment by Werkov** [comment]
Podle logů:

> fks_pdf_parser_exception
>
> Image file has no extension and no type was specified:

Je to IMO kvůli tomuto 7c69c4b60, není tam správná cesta ke QR obrázku (anebo monster commit se mstí).

**Comment by cevro** [comment]
To už je fixnuté tu:
https://github.com/fykosak/fksdb/pull/398/files#diff-62d50e3dce578407d2167c34b80690c9L109

Ani po tejto oprave to nebeží.

**Comment by Werkov** [comment]
Oh. V logách nevidím, další relevantní chybu. Na čem to končí tentokrát?

**Comment by cevro** [comment]
Log z localhosta, je to TeXový dokument. 

<title>Submits\ProcessingException</title>

BTW: preto ten debugger

**Comment by Werkov** [comment]
Co je ta vnořená výjimka?

**Comment by cevro** [comment]
@Werkov sry, github mi ju zakomentoval. Opravené

**Comment by Werkov** [comment]
Možná to je jen tvoje testovací PDF > 1.4?

https://stackoverflow.com/questions/12154190/fpdf-error-this-document-testcopy-pdf-probably-uses-a-compression-technique-w

**Comment by cevro** [comment]
Pravdepodobne to bude tým, pdf ostampovené zobrané z FKSDB mi nanovo prestampovalo.
