### ISSUE TITLE
Vysledkovky JQuery cashuje .data()

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#4]
JQuery .data() nereaguje na zmenu atribútu data-* a má nacashovanú prvú hodnotu uloženú do tohoto atribútu.

**Comment by Werkov** [comment]
AFAIK, .data() a data-* nejsou úplně to samé. Viz některé thready na [SO](http://stackoverflow.com/questions/7261619/jquery-data-vs-attr).

**Comment by cevro** [comment]
Riešenie:
ukaldanie aj do data-* attribútu aj do data tj. $.cashe  
```
...
.attr('data-points', submit.points)
.data('points', submit.points)
...
```
