### ISSUE TITLE
Počítání kapacity ubytování stejného doprovodu pro různé týmy

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#46]
Oproti neounu DB počíta kapacitu o jedna menšiu.

**Comment by Werkov** [comment]
Dokážeš na to napsat failující test, podobný [tomuto](https://github.com/fykosak/fksdb/blob/master/tests/Events/FormAdjustments/ResourceAvailability.secondary-limitok.phpt)?

**Comment by cevro** [comment]
OK tak počíta kapacitu dobre ale ale týmom "Ibyšta" a "Nějaký názov" sa podarilo zadať rovnakého učiteľa aj ubytovanie. A web ho vypísal len raz.

**Comment by Werkov** [comment]
Aha. Aktuálně ty `*Availability` adjustmenty umí kontrolovat jen prostě zadané pole. Taky bych neřekl, že to je bug. Ty týmy si prostě rezervovali dvakrát ubytování pro stejného učitele.

Změnil bych to, napsal bych jim, aby to neměnili zpět a pro naše účely udělal export, kde by se tohle kontrolovalo.

**Comment by cevro** [comment]
Zmenil som to týmu, čo sa neskôr registroval. A informoval som tým.

**Comment by cevro** [comment]
Vyriešené pridaním eventAccommodation, ktoré sa viaže person & event
