### ISSUE TITLE
Rozumné výchozí datum narození

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#47]
Využít parametr [`acYear`][1] a implementovat výchozí hodnotu datumu, pro očekávaný věk účastníka.

Cíl: zamezit vyplňování aktuálního data jako data narození.

Proti: když se na to pole někdo vykašle, je to alespoň vidět jako anomálie v datech. S touto úpravou to zanikne.

[1]: https://github.com/fykosak/fksdb/blob/master/app/Components/Forms/Factories/PersonFactory.php#L207

**Comment by LukasLedvina** [comment]
+1 proti.
Navrhuji variantu udělat export, co to bude detekovat před exportem do AESOPa, ideálně i před soutěží.

**Comment by timkol** [comment]
Solved by #161
