### ISSUE TITLE
Lepší UX pro zadavače

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#48]
@LukasLedvina s poukazem na Náboj junior navrhuje, že by se mělo zpříjemnit opisování kódu, a to dvěma způsoby:

- prefix (v našem případě asi nuly) mít předvyplněný tak, aby zadavač musel opsat opravdu pouze číslo týmu, kód úlohy a kontrolní součet
- omezit číslo týmu tak, aby bylo maximálně dvouciferné (např. prefixem kategorie) + protože je to tuším aktuálně e_fyziklani_team_id (který rychle roste), tak vytvořit nový klíč unikátní jen v rámci daného ročníku fyziklání (příp. dále omezit na kategorii a/nebo místnost, tak, aby byl (maximálně) dvouciferný).

**Comment by cevro** [comment]
Nad prvou častou som uvažoval, a som za.

Proti druhému som výrazne proti. Zadávač by musel mať niekdy predvyplnenú miestnosť/kategóriu. Pripadne by ju musel vyberať, čo spôsobí len zbytočné komplikácie a zabraňovalo by operatívnemu zadávaniu cross-rooms čo sa bežne deje. 
A týmov budeme mať 100+ teda či zadá 3 alebo 4 čísla je jedno.

**Comment by cevro** [comment]
Vcera som sa hral a napisal som novy input. Ked sa mergne dev-fof-new dam pull request.

**Comment by Werkov** [comment]
V rozsahu původního popisu by mělo výt vyřešeno v #49.
