### ISSUE TITLE
Nette zle parsuje numerické kluče polí

### ISSUE THREAD

**Issue by cevro** [fykosak/fksdb#53]
Pri načítavaní fyziklani, načítava nette eventy ako neindexované pole od indexu najmenšieho eventu teda namiesto 95 a 116 mám 95 a 96.

**Comment by timkol** [comment]
Caused by https://github.com/fykosak/fksdb/blob/fa967c41aaa414803686c6e9bc48272a06a1545e/libs/Nette/Config/Helpers.php#L37 (still in current version of nette/di)

Workaround: whole config in one file

**Comment by Werkov** [comment]
Když jsem psal testy, tak jsem si uvědomil, jaké je správné řešení. Jelikož každý pro FOF již existuje objekt `ModelEvent` (tabulka `event`), tak se tento obsah dá uložit jako parametry specifické pro tento typ akce.

**Comment by timkol** [comment]
myslíš nacpat to do data/events/fyziklani-*.neon? o tom u6 jsme se s @cevro bavili a nakonec se to dalo do data/fyziklani

**Comment by cevro** [comment]
Momentálne events slúžia skoro výhradne na prihlášky. Nerád by som plietol kombinoval parametre prihášok s nastavením fyzikláni, sú iné a riešia diametrálne odlišné veci.

**Comment by Werkov** [comment]
Mám na mysli [tohle](https://github.com/fykosak/fksdb/blob/master/data/events/fyziklani.neon#L67) a přístup k tomu přes něco jako [tento wrapper](https://github.com/fykosak/fksdb/blob/master/app/model/Events/Model/Holder/BaseHolder.php#L428).
Další výhoda je, že to lze upravovat přes GUI v parametrech akce.

Nechme to projít hlavami.

**Comment by Werkov** [comment]
Resolved in #95.
