### ISSUE TITLE
Neodesílat zadávací formulář stiskem Enteru

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#55]
Omylem se může odeslat za 5 bodů.

**Comment by cevro** [comment]
Osobne sa mi to nepáči:
http://stackoverflow.com/questions/11235622/jquery-disable-form-submit-on-enter

**Comment by Werkov** [comment]
Ještě mě napadlo -- nechat odesílání enterem, ale body zadávat přes radio-skupinu, která by defaultně byla prázdná, takže bys musel explicitně zvolit body, aby šlo to odeslání.

Tohle mi přijde ještě lepší, než prostý disable, neboť to lze pak ovládat celé klávesnicí.

**Comment by timkol** [comment]
Je to sice jeden stisk navíc, ale přijde mi to jako čisté řešení.
Akorát to radio to bude chtít přestylovat, minimálně aby byly puntíky
dostatečně velké.

**Comment by cevro** [comment]
Radio buttony tam historicky boli. Niekomu /uz neviem komu/ sa to nepacilo. Nieje problem to tam dodat. Inak sa mi radia pacia menej pretoze sa hlavne pri citaniz z QR to bude spomalovat.

**Comment by Werkov** [comment]
Můžou být obě varianty. QR uživatele můžem celkem dobře rozlišit (URL).

**Comment by timkol** [comment]
Víc variant bych nedělal, akorát to přidá starosti s údržbou a dokumentací.

**Comment by LukasLedvina** [comment]
Mohly by být radia ve dvou sloupečcích (počátečně nezatržená)? Alespoň pro mobil, aby to bylo větší a dále od sebe.

**Comment by cevro** [comment]
Radio komponent existuje využíva sa pri edistácii (nič nové nepribudne). 

Stačí aby sa ľudia naučili klikať na label a nie len nutne do kolečka netreba sa s tým moc hrať. Inak zväčšovať radio ne! Nejde to crossbrowser moc dobre a niektoré si to zle interpretujú a niektoré na to uplne kašlú.

**Comment by Werkov** [comment]
Ať už jakkkoli, rozhodně bych přidal parametr do URL, abychom věděli, že jde o QR input (ale to vlastně už existuje teď, neboť přes web se nikde taková URL nelinkuje...)

**Comment by cevro** [comment]
Rozpoznas to jednoducho, ak je vplnene `$id` ide o QR ak nie tak ide o rucne zadavanie. Ano mozes zadat QR kod do adresy, ale asi to nieje tak pohodlne.

**Comment by cevro** [comment]
Pre 12. ročník nechávam otvorené a nebude sa to fixovať. Každopádne ak sa nietko na to chce pozrieť potreba to opraviť v Reacte aj netteForms.
