### ISSUE TITLE
Zlepšit scrollování výsledkovek

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#57]
na spodku stojí moc dlouho
prostředek se moc rychle pohybuje

**Comment by cevro** [comment]
Napísať novu autoScroll triedu v TS(x)

**Comment by cevro** [comment]
Fix in https://github.com/fykosak/nette-brawl-lib/commit/94859016aa9ba9de52e539c8c13f9a1f3ac66ab8

**Comment by cevro** [comment]
Treba doposat animacie.

**Comment by cevro** [comment]
- nasadiť nové jQuery
- napísať animácie

**Comment by cevro** [comment]
jQuery.prototype.animate neuveritelne zere CPU.
