### ISSUE TITLE
Error 500 v přihláškách

### ISSUE THREAD

**Issue by Werkov** [fykosak/fksdb#67]
Reprodukce:
- jako org se přihlásit
- měl by se zobrazit odkaz na účastnický dashboard
- když jdu na [stránku s přihláškami](https://db.fykos.cz/fykos30/application/list?bc=xOAw), dostanu 500

Stalo se to 2017-01-24 23:15 (+/- 5 minut, mělo by to být v logu).

**Comment by Werkov** [comment]
@timkol To my mohlo být taky #91.

**Comment by timkol** [comment]
@Werkov Podle logu to je ono, zavírám.
