### ISSUE TITLE
Move XSL from fykos.cz to db.fykos.cz

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#77]
Would help with versioning, also most of them are used in conjunction with FKSDB WSDL.

Alternatively move all XSL files to it's own repository.

**Comment by Werkov** [comment]
I agree the interface description (WSDL) should be versioned together with its implementation (FKSDB). We only must ensure that up to date version is exposed at configured URL, i.e. possibly change the URL (not sure if all clients would be able to follow redirects).

**Comment by timkol** [comment]
Solved by #160
