### ISSUE TITLE
Upozornění na zadávání bodů staré série

### ISSUE THREAD

**Issue by timkol** [fykosak/fksdb#78]
@syselkk
Chtělo by to nějak zvýraznit u bodování a raději i zadávání došlých
řešení, kterou sérii tam zadává uživatel - tedy aby se při otevření té
stránky otevřela s varovnou hláškou v červené barvě v nějakém znění ve
smyslu - "Zadáváš body XXX. série YYY. ročníku - pokud chceš zadávat jinou
sérii a jiný ročník, vpravo nahoře rozklikni číslo série či číslo ročníku a
vyber si." Lidi si tohle prostě nepamatujou a jiný řešení, než varování
uživatele nejde asi udělat, pokud tam má být přístupný to, že můžou
zadávat/upravovat body i zpětně apod. ...

**Comment by Werkov** [comment]
FTR 77d636137a3b7107d5bd6db3fe98d44b395a1074 (pomocná změna)
