### ISSUE TITLE
user input validation for events 

### ISSUE THREAD

**Issue by rzehumat** [fykosak/fksdb#907]
Not strict user input check causes issues with typesetting. A more strict user input validation may be helpful in order not to painfully escape every individual team manually. 

**Example**
We allow both LaTeX character codes and unicode. Therefore both `ναμε` and `\nu\alpha\mu\epsilon` would pass. 
That is IMO bad practice. What about 
`Team name:` `ναμε`
`Warning: Use LaTeX commands to type Greek`
`Team name:` `\nu\alpha\mu\epsilon`
`Warning: LaTeX command "\nu" allowed in math mode only`
`Team name:` `$\nu\alpha\mu\epsilon$` -> correct

**Comment by cevro** [comment]
It's already solved, but FOL does not use that rules.

see: https://github.com/fykosak/fksdb/blob/master/data/events/fyziklani/fyziklani14.neon#L244

**Comment by cevro** [comment]
Sry, I was wrong, FOL also uses that rule, the character list is restricted to `\p{Latin}\p{Greek}\p{Cyrillic}\x{0020}-\x{00FF}]+$`.

Because of the character list is restricted, is probably best way  make a script, that converts characters to macros after download.
