### ISSUE TITLE
Umožnit opravovatelům stahovat .bak verzi řešení

### ISSUE THREAD

**Issue by vanekm** [fykosak/fksdb#949]
Některá řešení absolutně rozbijí skripty na přidávání hlaviček se jmény řešitelů, pak to musí řešit správce přijmu řešení.
Úkolem by tu bylo umožnit opravovatelům stahovat z fksdb .bak verzi řešení (tu originální před tím, než se skriptem rozbila). 
Stahování řešení je už impementované v inbox/list of submits (ale jen NONbak verze, tedy ta s hlavičkou, a jen pro správce přijmu řešení + vyšší práva v db).

**Comment by cevro** [comment]
Opravovateľ by správne nemal žiadne riešenia si sám sťahovať, a všetky tieto požiadavky by mal smerovať na správcu príjmu riešení, ktorý ma prehľad o riešeniach, prip. mu vie poskytnúť správnu verziu napr. v prípade problémov s uploadom resp. riešení zaslaných emailov a pod. Z tohoto dôvodu sú práva nastavené, tak ako sú.
