### ISSUE TITLE
UI glitch 

### ISSUE THREAD

**Issue by sstenchlak** [fykosak/fksdb#959]
https://db.fykos.cz/org/fykos34/series4/person/detail/18127

**Comment by sstenchlak** [comment]
TypeError: Argument 1 passed to FKSDB\Models\ORM\Models\AbstractModelSingle::createFromActiveRow() must be an instance of Nette\Database\Table\ActiveRow, null given, called in /network/data/www/fykos/db.fykos.cz/app/Models/ORM/Models/ModelPersonHistory.php on line 22 in /network/data/www/fykos/db.fykos.cz/app/Models/ORM/Models/AbstractModelSingle.php:16

**Comment by cevro** [comment]
Fixed
