### ISSUE TITLE
Implement html certificates for FOF/FOL teams 

### ISSUE THREAD

**Issue by rzehumat** [fykosak/fksdb#963]
We could create FOL/FOF certificates for teams in db using HTML to PDF instead of making the certificates locally via LaTeX (time consumption is terrible in current solution).

**Comment by rzehumat** [comment]
## My TODO list
### Everything should be DRY and fast, target `1e+4` certificates per hour

- `js` script to get `team` from `db` (`str teamName`, `array teamMembers`, `str teamSchool`, `str teamCat`, `array [teamPlaceCat, teamPlaceTot]`)
- `js` script to get `eventInfo` from `db` (`dict eventName {cs: eventNameCs, en: eventNameEn}`, `dict committeeMemberFunction: {commiteeMemberName, committeeMemberImage}`, `dict eventWeb {webCs: eventWebCs, webEn: eventWebEn}`, `dict eventFooter {cs: eventFooterCs, en: eventFooterEn}`)
- `js` script to convert from `html` to `pdf`

### Files
- `html` skeleton -- `lang`-independent
- `css` styles -- `lang`-independent
- `js` scripts -- will include `lang` conditions

**Comment by sstenchlak** [comment]
I am a little bit skeptical. The question is whether we want to generate everything in FKSDB or use Astrid instead. I am afraid that the naive implementation, where FKSDB would contain an HTML of diplomas, would be too cumbersome (files in Astrid are easier to modify than publishing a new FKSDB version). Also, by doing it, we say that there is another possible way to generate PDFs and therefore creating ambiguity (yes, I am aware of Fyziklani's seating plan).

I suggest using Astrid to generate HTML files and convert them manually to PDF or programmatically using a Chromium core. And anything but Python. (Or, use FKSDB but make it more robust and universal.)
