### ISSUE TITLE
Možnost založit školu při odesílání příhlášky

### ISSUE THREAD

**Issue by sstenchlak** [fykosak/fksdb#987]
Vyžaduje diskuzi, ale chceme nějak týmům umožnit se zaregistrovat i přes to, že jejich škola není ve FKSDB.

Například by mohli školu založit oni a my ji pouze schválíme, přičemž i neschválená škola se zobrazí v seznamu škol, aby se do ní už mohly týmy přihlašovat.

**Comment by cevro** [comment]
Duplicitne viď https://github.com/fykosak/fksdb/issues/206
